plugins {
    id 'net.fabricmc.fabric-loom' version '1.16.1'
    id 'maven-publish'
}

version = '1.0.0'
group = 'com.shieldoptimization'

base {
    archivesName = 'ShieldOptimization'
}

repositories {
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "shieldoptimization" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft 'com.mojang:minecraft:26.1.2'
    implementation 'net.fabricmc:fabric-loader:0.19.3'
    implementation 'net.fabricmc.fabric-api:fabric-api:0.155.2+26.1.2'
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property 'archivesName', project.name
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
        }
    }
}
